name: Docker
on:
  push:
    branches: [ "main" ]
  
jobs:
  publish_image:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: microsoft/variable-substitution@v1
        with:
          files: '${{ github.workspace }}/API/appsettings.json'
        env:
          ConnectionStrings.DefaultConnection: Server=db;Database=eclipse-works;User Id=sa;Password=A1B2C3@123;TrustServerCertificate=true

      - name: build
        run: |
          DOCKER_USERNAME=brunovbs
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          IMAGE_VERSION=1.0.1
          docker build . -t $DOCKER_USERNAME/$REPO_NAME:$IMAGE_VERSION

      - name: publish
        run: |
          docker login -u brunovbs -p ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USERNAME=brunovbs
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          IMAGE_VERSION=1.0.1
          docker push $DOCKER_USERNAME/$REPO_NAME:$IMAGE_VERSION